/*
===============================================================================
Analysis: Revenue by Department
File: 04_revenue_by_department.sql
===============================================================================

Objective
---------
Compare the revenue generated by each product department.

Business Context
----------------
This analysis provides a high-level view of sales performance by department.
It helps identify which department contributes the most to the company's
revenue and supports strategic decisions regarding inventory allocation,
marketing investment and product assortment.

Business Rule
-------------
- Only completed sales are considered (status = 'Complete').
- Revenue is calculated using the sale_price of each sold item.
- Revenue is aggregated at the department level.

Source Tables
-------------
- order_items (fact table)
- products (product dimension)

Output
------
Returns one row per department containing:
- department
- department_revenue

The result is sorted from the highest to the lowest revenue.
===============================================================================
*/

SELECT p.department AS department, ROUND(SUM(od.sale_price),2) AS department_revenue
FROM `bigquery-public-data.thelook_ecommerce.order_items` od
JOIN `bigquery-public-data.thelook_ecommerce.products` p ON p.id = od.product_id
WHERE od.status = 'Complete'
GROUP BY department
ORDER BY department_revenue DESC;