/*
===============================================================================
Analysis: Revenue by Department
File: 04_revenue_by_department.sql
===============================================================================

Objective
---------
Compare the revenue generated by each product department.

Business Context
----------------
This analysis provides a high-level view of sales performance by department.
It helps identify which department contributes the most to the company's
revenue and supports strategic decisions regarding inventory allocation,
marketing investment and product assortment.

Business Rule
-------------
- Only completed sales are considered (status = 'Complete').
- Revenue is calculated using the sale_price of each sold item.
- Revenue is aggregated at the department level.

Source
------
- analytics.vw_sales

Notes
-----
This query uses the analytical view (vw_sales), created during Sprint 4,
which consolidates sales, product and customer information into a single
analytical layer.

Output
------
Returns one row per department containing:
- department
- department_revenue

The result is sorted from the highest to the lowest revenue.
===============================================================================
*/

SELECT department, ROUND(SUM(sale_price),2) AS department_revenue
FROM `projeto-e-commerce-501019.analytics.vw_sales`
WHERE status = 'Complete'
GROUP BY department
ORDER BY department_revenue DESC;