/*
===============================================================================
Analysis: Revenue by Country
File: 07_revenue_by_country.sql
===============================================================================

Objective
---------
Compare the revenue generated by each country to identify the company's most
important international markets.

Business Context
----------------
This analysis provides a geographical overview of the business by highlighting
which countries contribute the most to total revenue. It supports strategic
decisions related to international expansion, regional marketing initiatives,
logistics planning and commercial prioritization.

Business Rule
-------------
- Only completed sales are considered (status = 'Complete').
- Revenue is calculated using the sale_price of each sold item.
- Revenue is aggregated at the country level.
- All countries are included to provide a complete geographical view of the business.

Source Tables
-------------
- order_items (fact table)
- users (customer dimension)

Output
------
Returns one row per country containing:
- country
- country_revenue

The result is sorted from the highest to the lowest revenue.
===============================================================================
*/

SELECT u.country AS country, ROUND(SUM(od.sale_price),2) AS country_revenue
FROM `bigquery-public-data.thelook_ecommerce.order_items`od
JOIN `bigquery-public-data.thelook_ecommerce.users` u ON u.id = od.user_id
WHERE od.status = 'Complete'
GROUP BY u.country
ORDER BY country_revenue DESC;
