/*
===============================================================================
Analysis: Revenue by Country
File: 07_revenue_by_country.sql
===============================================================================

Objective
---------
Compare the revenue generated by each country to identify the company's most
important international markets.

Business Context
----------------
This analysis provides a geographical overview of the business by highlighting
which countries contribute the most to total revenue. It supports strategic
decisions related to international expansion, regional marketing initiatives,
logistics planning and commercial prioritization.

Business Rule
-------------
- Only completed sales are considered (status = 'Complete').
- Revenue is calculated using the sale_price of each sold item.
- Revenue is aggregated at the country level.
- All countries are included to provide a complete geographical view of the business.

Source
------
- analytics.vw_sales

Notes
-----
This query uses the analytical view (vw_sales), created during Sprint 4,
which consolidates sales, product and customer information into a single
analytical layer.

Output
------
Returns one row per country containing:
- country
- country_revenue

The result is sorted from the highest to the lowest revenue.
===============================================================================
*/

SELECT country, ROUND(SUM(sale_price),2) AS country_revenue
FROM `projeto-e-commerce-501019.analytics.vw_sales`
WHERE status = 'Complete'
GROUP BY country
ORDER BY country_revenue DESC;
